package fi.vrk.xroad.catalog.persistence.entity;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.UUID;

@Entity
@Getter
@Setter
@ToString(exclude = "service")
public class Wsdl {
    @Id
    @Column(nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "WSDL_GEN")
    @SequenceGenerator(name = "WSDL_GEN", sequenceName = "WSDL_ID_SEQ", allocationSize = 1)
    private long id;
    @ManyToOne
    @JoinColumn(name = "SERVICE_ID")
    private Service service;
    // this is not lazy loaded since hibernate would need build-time bytecode enhancement
    // this could be optimized e.g. by not mapping this data to JPA entity, and
    // fetching it directly with a native query
    @Basic(fetch = FetchType.LAZY)
    @Column(length = 40000) // big enough so that autogenerated tables can fit test data
    private String data;
    @Column(nullable = false)
    private String externalId;
    @Embedded
    private StatusInfo statusInfo = new StatusInfo();

    public Wsdl() {
    }

    public Wsdl(Service service, String data, String externalId) {
        this.service = service;
        this.data = data;
        this.externalId = externalId;
        statusInfo.setTimestampsForNew(LocalDateTime.now());
    }

    public void initializeExternalId() {
        externalId = System.currentTimeMillis() + "_" + UUID.randomUUID().toString();
    }
}
