package fi.vrk.xroad.catalog.persistence.entity;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.*;
import java.util.Date;

@Entity
@Getter
@Setter
@ToString(exclude = "service")
public class Wsdl {
    @Id
    @Column(nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "WSDL_GEN")
    @SequenceGenerator(name = "WSDL_GEN", sequenceName = "WSDL_ID_SEQ", allocationSize = 1)
    private long id;
    @OneToOne(optional=false)
    @JoinColumn(name="SERVICE_ID", unique=true, nullable=false, updatable=false)
    private Service service;
    @Column(length = 40000) // big enough so that autogenerated tables can fit test data
    private String data;
    private String dataHash;
    private String externalId;
    @Embedded
    private StatusInfo statusInfo = new StatusInfo();

    public Wsdl() {
    }

    public Wsdl(Service service, String data, String dataHash, String externalId) {
        this.service = service;
        this.data = data;
        this.dataHash = dataHash;
        this.externalId = externalId;
        statusInfo.setTimestampsForNew(new Date());
    }

    public Wsdl(Service service, String data, String dataHash, String externalId, Date created, Date updated, Date removed) {
        this.service = service;
        this.data = data;
        this.dataHash = dataHash;
        this.externalId = externalId;
        statusInfo.setCreated(created);
        statusInfo.setUpdated(updated);
        statusInfo.setRemoved(removed);
    }
}
